version: '3.8'

services:
  nearbuy-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
    container_name: nearbuy-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  nearbuy-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80"
    container_name: nearbuy-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev 